export const GET_CHAT_DATA = 'GET_CHAT_DATA';
export const CHANGE_CHAT_DIALOG = 'CHANGE_CHAT_DIALOG';
export const ADD_CHAT_IN_CHATBOX = 'ADD_CHAT_IN_CHAT';
export const SELECT_CHAT = 'SELECT_CHAT';
export const TOGGLE_FRIEND_ONLINE = 'TOGGLE_FRIEND_ONLINE';
